# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
install:
  - pip install --user --upgrade pip
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user -U scikit-learn
