# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
install:
  - pip install --upgrade pip
  - pip install numpy
  - pip install scipy
  - pip install -U scikit-learn
