# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/R/Library
before_cache:
    - export R_LIB_USER=$HOME/R/Library
before_install:
  - pip install --user --quiet --upgrade pip
  - pip install --user --quiet numpy
  - pip install --user --quiet scipy
  - pip install --user --quiet -U scikit-learn
